# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: miralagustiansyam/tutorial-cicd-github-actions:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '343.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure gcloud settings
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set app/promote_by_default false

      - name: Deploy to GCP
        run: |
          gcloud app deploy --image-url=miralagustiansyam/tutorial-cicd-github-actions:latest --quiet

      - name: Clean up
        run: docker logout && gcloud auth revoke
